base_data_path: "/home/ojas/data/dnd/Session_1/"
metrics_to_run:
  - beat_consistency
  - sdtw
  - cross_beat_consistency
bvh_audio_folder_paths:
  person1:  
    bvh: "${base_data_path}/a/a_chunks/"
    zarr: "${base_data_path}/a/a_world_pos.zip"
    audio: "${base_data_path}/a/a_delay_m0.5/"
  person2:
    bvh: "${base_data_path}/c/c_chunks/"
    zarr: "${base_data_path}/c/c_world_pos.zip"
    audio: "${base_data_path}/c/c_delay_m0.5/"
  person3:
    bvh: "${base_data_path}/b/b_chunks/"
    zarr: "${base_data_path}/b/b_world_pos.zip"
    audio: "${base_data_path}/b/b_delay_m0.5/"
  person4:
    bvh: "${base_data_path}/j/j_chunks/"
    zarr: "${base_data_path}/j/j_world_pos.zip"
    audio: "${base_data_path}/j/j_delay_m0.5/"
  person5:
    bvh: "${base_data_path}/l/l_chunks/"
    zarr: "${base_data_path}/l/l_world_pos.zip"
    audio: "${base_data_path}/l/l_delay_m0.5/"
rqa_settings:
  recurrence_rate: 0.02
  indiv_joints:
    - LeftHand
    - RightHand
    - LeftArm
    - RightArm
  joint_pair_rec:
    - [ LeftHand, RightHand ]
    - [ LeftArm, RightArm ]
emd_settings:
  cross_person: true

sdtw_settings:
  cross_person: true
