joint_params:
  LeftArm:
    damping_factor: 0.9
    iterations: 8
    sigma: 10
  LeftForeArm:
    damping_factor: 0.9
    iterations: 8
    sigma: 10
  LeftHand:
    damping_factor: 0.9
    iterations: 8
    sigma: 10
  RightArm:
    damping_factor: 0.9
    iterations: 8
    sigma: 10
  RightForeArm:
    damping_factor: 0.9
    iterations: 8
    sigma: 10
  RightHand:
    damping_factor: 0.9
    iterations: 8
    sigma: 10
