joint_params:
  LeftArm:
    damping_factor: 0.9
    iterations: 8
    sigma: 40
  LeftForeArm:
    damping_factor: 0.9
    iterations: 8
    sigma: 40
  LeftHand:
    damping_factor: 0.9
    iterations: 8
    sigma: 20
  RightArm:
    damping_factor: 0.9
    iterations: 8
    sigma: 40
  RightForeArm:
    damping_factor: 0.9
    iterations: 8
    sigma: 40
  RightHand:
    damping_factor: 0.9
    iterations: 8
    sigma: 20
