recurrence_radius: 0.2
bvh_files: "${here:}/samples/"
audio_files: "${here:}/samples/"
joints:
  - LeftHand
  - LeftArm
  # - LeftForeArm
  # - RightHand
  # - RightArm
  # - RightForeArm
metrics:
  individual:
    recurrence:
      - rqa_metrics
    beat_consistency:
      - compute_becemd
  pairwise:
    recurrence:
      - rqa_metrics
    beat_consistency:
      - compute_becemd
