recurrence_radius: 0.2
bvh_file: ${here:}/samples/c-cut.bvh
audio_file: ${here:}/samples/c-clean-30.wav
joints:
  - LeftHand
  - LeftArm
  - LeftForeArm
  - RightHand
  - RightArm
  - RightForeArm
metrics:
  individual:
    recurrence:
      - rqa_metrics
    beat_consistency:
      - compute_becemd
  pairwise:
    recurrence:
      - rqa_metrics
    beat_consistency:
      # - compute_becemd
