base_data_path: "/home/ojas/data/dnd/Session_1/"
metrics_to_run:
  - indiv_rqa
  - crqa
  - beat_consistency
  - sdtw
  - cross_beat_consistency
bvh_audio_folder_paths:
  person1:
    bvh: "${base_data_path}/a/delayed_bvh/"
    zarr: "${base_data_path}/a/a_pos_delayed.zip"
    audio: "${base_data_path}/a/audio_segments/"
  person2:
    bvh: "${base_data_path}/c/delayed_bvh/"
    zarr: "${base_data_path}/c/c_pos_delayed.zip"
    audio: "${base_data_path}/c/audio_segments/"
  person3:
    bvh: "${base_data_path}/b/delayed_bvh/"
    zarr: "${base_data_path}/b/b_pos_delayed.zip"
    audio: "${base_data_path}/b/audio_segments/"
  person4:
    bvh: "${base_data_path}/j/delayed_bvh/"
    zarr: "${base_data_path}/j/j_pos_delayed.zip"
    audio: "${base_data_path}/j/audio_segments/"
  person5:
    bvh: "${base_data_path}/l/delayed_bvh/"
    zarr: "${base_data_path}/l/l_pos_delayed.zip"
    audio: "${base_data_path}/l/audio_segments/"
rqa_settings:
  threshold: 0.5
  recurrence_rate: 0.02
  indiv_joints:
    - LeftHand
    - RightHand
    - LeftArm
    - RightArm
  joint_pair_rec:
    - [ LeftHand, RightHand ]
    - [ LeftArm, RightArm ]
emd_settings:
  cross_person: true

sdtw_settings:
  cross_person: true
